### ISSUE TITLE
PhenoGraph does not accept seed

### ISSUE THREAD

**Issue by DenisSch** [BodenmillerGroup/histoCAT#14]
As reported by several users PhenoGraph does not accept the seed from Matlab. @votti @JanaFischer any ideas for a work around?

**Comment by votti** [comment]
Hi,
The 'issue' is that currently HistoCAT is calling the `louvain` clustering via a systems call:
https://github.com/BodenmillerGroup/histoCAT/blob/6ad66331387a3afd4841ce6299402add8bfdf3f0/histoCAT/3rdParty/PhenoGraph/LouvainfromBin.m#L28

That means the matlab random seed will not affect this call.
The `Louvain` c++ code is random due to the following line: 
https://github.com/BodenmillerGroup/histoCAT/blob/6ad66331387a3afd4841ce6299402add8bfdf3f0/histoCAT/3rdParty/PhenoGraph/Louvain_d/community.cpp#L278

Which is used in the command line call: 
https://github.com/BodenmillerGroup/histoCAT/blob/6ad66331387a3afd4841ce6299402add8bfdf3f0/histoCAT/3rdParty/PhenoGraph/Louvain_d/main_community.cpp#L141

Currently, the random seed is set as a function of time:
https://github.com/BodenmillerGroup/histoCAT/blob/bb14e391ce98ae61aaf22df0f055a4df9990b78a/histoCAT/3rdParty/PhenoGraph/Louvain_d/main_community.cpp#L115

My suggestion would be to add a command line argument 'random_seed' to the `main_community.cpp` and use this instead as a seed, if provided.
